analysis:
  run_modal: True
  run_pushpull: False
  run_timehistory: False
  run_IDA: True

moment_rotation_options:
  pt_points: 5
  use_GM: True
  steel_failure: True
  tendon_failure: True
  beta: 0.6 # shear area for a rectangular section

model_options:
  transformation: 2   # 1 Linear, 2 PDelta
  rigid_joints: False
  rigid_factor: 1000
  rigid_link: 1000000000
  frame_damping: 0.03 # Elastic Damping

output_options:
  print_model: True # Saves a json with model data

ida_options:
  initial_int_measure: 0.25
  initial_step: 0.6  # This is times the initial_int measure
  max_iter_ida: 6

performance_options:
  processes: 7 # Number of processes you want to allocate for TH ONLY




